project:
  type: website
  output-dir: docs

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  sidebar:
    style: "docked"
    contents:
          - viz_1_ggplot.qmd
          - viz_2_exploratoryAnalysis.qmd
          - viz_3_exemplarVisualizations.qmd
          - viz_4_building_better.qmd
          - viz_start_to_finish.qmd
    tools: 
      - icon: github
        href: https://github.com/tylermcinnes/visualization_day  


format:
  html:
    mainfont: "sarif"
    monofont: "monospace"
    fontsize: 18px
    theme: cosmo
    css: styles.css

